# -*- coding: utf-8 -*-
"""Data_Eng_A1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16gGPVGjC_oAwykbFIBgo-JxTmGZ2bCAU

# **FuelCheck Data Retrieval and Processing**
## COMP5339 Project Assignment Stage 1

- Adnan Ali (540372210)
- Akarsh kumar (540892291)
- Akshat Jain  (540775374)
- Annie Shorya (540540853)
- Kevin Ninan Mathew (540489161)

## **Loading Libraries**
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import os
import re
import seaborn as sns
import matplotlib.pyplot as plt
import duckdb

"""## **Data Retrieval**"""

# Target webpage
url = "https://data.nsw.gov.au/data/dataset/fuel-check"

# Getting HTML content using requests + BeautifulSoup
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")

# Extractracting all links ending with .csv or .xlsx for 2024 and 2025
data_dir = "fuelcheck_data"
os.makedirs(data_dir, exist_ok=True)

all_links = []
pattern = re.compile(r"(2024|2025|24|25)\.(csv|xlsx)$", re.IGNORECASE)


for link in soup.find_all("a", href=True):
    href = link["href"]
    if not href.endswith((".csv", ".xlsx")):
        continue
    if pattern.search(href):
        full_url = href if href.startswith("http") else "https://data.nsw.gov.au" + href
        all_links.append(full_url)
print("2024 and 2025 data retrieved successfully in fuelcheck_data/.")

"""## **Data Integration**"""

# Downloading and reading each file
all_dfs = []

for file_url in all_links:
    file_name = file_url.split("/")[-1]
    print(f"Downloading {file_name}")

    file_path = os.path.join(data_dir, file_name)
    try:
        res = requests.get(file_url)
        with open(file_path, "wb") as f:
            f.write(res.content)
        print(f"Saved to {file_path}")

        # Reading into DataFrame
        if file_path.endswith(".csv"):
            df = pd.read_csv(file_path)
        elif file_path.endswith(".xlsx"):
            df = pd.read_excel(file_path)
        else:
            continue

        all_dfs.append(df)

    except Exception as e:
        print(f"Error with {file_name}: {e}")

# Merging all into one DataFrame
combined_df = pd.concat(all_dfs, ignore_index=True)

# Saved merged DataFrame as a CSV file
combined_df.to_csv("fuelcheck_combined_2024_2025.csv", index=False)
print("Merged all data into 'fuelcheck_combined_2024_2025.csv'")

combined_df.head(10)

print(combined_df.dtypes)

combined_df.shape

"""## **Data Preprocessing**"""

# Standardizing column names
combined_df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# Renaming to more simpler names
combined_df.rename(columns={
    "servicestationname": "station_name",
    "priceupdateddate": "last_updated",
    "fuelcode": "fuel_type"
}, inplace=True)

# Making text columns uniform

text_cols = ["station_name", "address", "suburb", "brand", "fuel_type"]
for col in text_cols:
    combined_df[col] = combined_df[col].astype(str).str.strip().str.title()

# Converting data types for price and last_updated

combined_df["price"] = pd.to_numeric(combined_df["price"], errors="coerce")
combined_df["last_updated"] = pd.to_datetime(combined_df["last_updated"], errors="coerce")

# Dropping rows with missing values

combined_df.dropna(subset=["station_name", "address", "suburb", "postcode", "fuel_type", "price", "last_updated"], inplace=True)

# Removing duplicates

df.drop_duplicates(inplace=True)

combined_df.head()

# Distributing date info in different entities

combined_df["last_updated_year"] = combined_df["last_updated"].dt.year.astype("int32")
combined_df["last_updated_day"] = combined_df["last_updated"].dt.day.astype("int8")
combined_df["last_updated_month"] = combined_df["last_updated"].dt.month.astype("int8")
combined_df["last_updated_time"] = combined_df["last_updated"].dt.time
combined_df = combined_df.drop("last_updated", axis=1)
print(combined_df.dtypes)
combined_df

# Creating members_only column based on station_name

combined_df["members_only"] = combined_df["station_name"].str.contains(r"\(Members Only\)", case=False, na=False)

# Removing Members Only key from station_name

combined_df["station_name"] = combined_df["station_name"].str.replace("(Members Only)", "", regex=False).str.strip()

combined_df.shape

print(combined_df.dtypes)
combined_df

"""## **Data Exploration**

### **General Visualisation**

### Average Price by Brand
"""

# Setting Seaborn style for the plot background
sns.set(style="whitegrid")

# Groupping the DataFrame by 'brand'
# calculating mean fuel price for each brand,
brand_price = combined_df.groupby("brand")["price"].mean().sort_values(ascending=False)
plt.figure(figsize=(10, 6)) # Defining Size
sns.barplot(x=brand_price.values, y=brand_price.index, palette="viridis")
plt.title("Average Fuel Price by Brand") # Tittle
plt.xlabel("Average Price (cents)") # Labelling
plt.ylabel("Brand")
plt.show()

"""### Price distribution across 10 most frequesnt suburbs"""

top_suburbs = combined_df["suburb"].value_counts().head(10).index

# Filtering data to include only these suburbs
top_suburb_data = combined_df[combined_df["suburb"].isin(top_suburbs)]

# Creating the boxplot
plt.figure(figsize=(14, 6))
sns.boxplot(data=top_suburb_data, x="suburb", y="price", palette="Spectral")
plt.title("Fuel Price Distribution by Top 10 Suburbs")
plt.xlabel("Suburb")
plt.ylabel("Price (cents)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### Price per fuel type"""

plt.figure(figsize=(10, 6))

# Creating a boxplot to show the distribution of fuel prices for each fuel type
sns.boxplot(data=combined_df, x="fuel_type", y="price", palette="Set3")
plt.title("Fuel Price Distribution by Fuel Type") # Title
plt.xlabel("Fuel Type") # Label
plt.ylabel("Price (cents)")
plt.grid(True)
plt.tight_layout()
plt.show()

"""### **Time-based Visualisation**

### Fuel prices across the months
"""

monthly_price = combined_df.groupby("last_updated_month")["price"].mean()

plt.figure(figsize=(10, 6)) # Sizeing
sns.lineplot(x=monthly_price.index, y=monthly_price.values, marker="o")
plt.title("Average Fuel Price by Month") # title

plt.xlabel("Month")
plt.ylabel("Average Price (cents)")
plt.xticks(range(1, 13))
plt.grid(True)
plt.show()

"""### Heatmap of Average Prices by Day & Month"""

# Creating a pivot table
heatmap_data = combined_df.pivot_table(
    index="last_updated_day",
    columns="last_updated_month",
    values="price",
    aggfunc="mean"
)

plt.figure(figsize=(12, 6))

# Making heatmap
sns.heatmap(heatmap_data, cmap="YlOrRd", annot=False)
plt.title("Average Fuel Price by Day and Month") # Title
plt.xlabel("Month") # Label
plt.ylabel("Day")
plt.show()

"""### Monthly Average Fuel Price by Brand and Fuel Type"""

monthly_avg = (
    combined_df
    .groupby(["last_updated_month", "brand", "fuel_type"])["price"]
    .mean()
    .reset_index()
)
# Filtering
top_brands = combined_df["brand"].value_counts().head(5).index
monthly_avg = monthly_avg[monthly_avg["brand"].isin(top_brands)]

# Plotting using seaborn catplot
sns.set(style="whitegrid")
g = sns.catplot(
    data=monthly_avg,
    x="last_updated_month",
    y="price",
    hue="fuel_type",
    col="brand",
    kind="bar",
    height=5,
    aspect=1.2,
    palette="Set2"
)

g.set_axis_labels("Month", "Avg Fuel Price (cents)")
g.set_titles("Brand: {col_name}")
g.fig.suptitle("Monthly Average Fuel Price by Brand and Fuel Type", y=1.03)
plt.tight_layout()
plt.show()

"""### **Exploration for Mapping in Stage 2**

### Brand Distribution per suburb
"""

# Filtering data to top 10 suburbs
filtered_df = combined_df[combined_df["suburb"].isin(top_suburbs)]

# Counting unique station names per brand per suburb
brand_spread = (
    filtered_df.groupby(["suburb", "brand"])["station_name"]
    .nunique()
    .unstack(fill_value=0)
)

# Plotting as stacked bar chart
brand_spread.plot(kind="bar", stacked=True, figsize=(14, 6), colormap="tab20")
plt.title("Fuel Brand Distribution Across Top 10 Suburbs")
plt.xlabel("Suburb")
plt.ylabel("Number of Stations")
plt.xticks(rotation=45)
plt.legend(title="Brand", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

"""### Average fuel prices across different suburbs and fuel types"""

# Creating a pivot table with average price
heatmap_data = filtered_df.pivot_table(
    index="suburb",
    columns="fuel_type",
    values="price",
    aggfunc="mean"
)

# Plotting the heatmap
plt.figure(figsize=(12, 6))
sns.heatmap(heatmap_data, annot=True, fmt=".1f", cmap="YlOrRd")
plt.title("Average Fuel Price by Suburb and Fuel Type")
plt.xlabel("Fuel Type")
plt.ylabel("Suburb")
plt.tight_layout()
plt.show()

"""### **Relationship Exploration**

### Fuel Price Distribution for Members Only vs Public
"""

plt.figure(figsize=(10, 6))

# Creating a boxplot comparing fuel prices between members-only and public stations
sns.boxplot(data=combined_df, x="members_only", y="price", palette="coolwarm")
plt.title("Fuel Price Distribution: Members Only vs Public Stations") # Title
plt.xlabel("Members Only") # Label
plt.ylabel("Price (cents)")
plt.show()

"""### Data Augmentation"""

# Loading selected dataset
newdata = pd.read_csv("Petrol_Stations.txt")
newdata

# Preprocessing the dataset for augmentation

newdata["members_only"] = newdata["station_name"].str.contains(r"\(Members Only\)", case=False, na=False)
newdata["station_name"] = newdata["station_name"].str.replace("(Members Only)", "", case=False, regex=False).str.strip()

# Creating Augmented df

original_df = combined_df
newdata_df = newdata

# Cleaning strings
def clean_string(s):
    if pd.isnull(s):
        return ""
    return str(s).strip().lower()

def get_street_name(s):
    return s.split(",")[0]

# Generating join key
original_df["station_key"] = original_df["station_name"].apply(clean_string) + "|" + \
                             original_df["members_only"].apply(clean_string) + "|" + \
                             original_df["suburb"].apply(clean_string) + "|" + \
                             original_df["postcode"].astype(str)

newdata_df["station_key"] = newdata_df["station_name"].apply(clean_string) + "|" + \
                            newdata_df["members_only"].apply(clean_string) + "|" + \
                            newdata_df["station_suburb"].apply(clean_string) + "|" + \
                            newdata_df["station_postcode"].astype(str)

# Normalizing station table post augmentation
stations_df = (
    original_df[["station_key", "station_name", "address", "suburb", "postcode", "brand"]]
    .drop_duplicates("station_key")
    .merge(newdata_df[["station_key", "X", "Y"]], on="station_key", how="left")
    .drop_duplicates("station_key")
    .reset_index(drop=True)
)
stations_df["station_id"] = stations_df.index + 1

# Normalizing fuel prices post augmentation
fuel_prices_df = original_df.merge(
    stations_df[["station_key", "station_id"]],
    on="station_key",
    how="left"
)[["station_id", "fuel_type", "price", "last_updated_year", "last_updated_month",
   "last_updated_day", "last_updated_time", "members_only"]]

stations_df

fuel_prices_df

"""### Data Transformation and Storage"""

# pip install duckdb

# Saving to DuckDB
con = duckdb.connect("fuel_data_normalized.duckdb")

con.execute("""
    CREATE OR REPLACE TABLE stations AS
    SELECT
        station_id,
        station_name,
        address,
        suburb,
        postcode,
        brand,
        X AS longitude,
        Y AS latitude
    FROM stations_df
""")

con.execute("""
    CREATE OR REPLACE TABLE fuel_prices AS
    SELECT
        station_id,
        fuel_type,
        price,
        last_updated_year,
        last_updated_month,
        last_updated_day,
        last_updated_time,
        members_only
    FROM fuel_prices_df
""")

# Sample query of join
result = con.execute("""
    SELECT
        s.station_name,
        s.suburb,
        s.postcode,
        s.latitude AS y,
        s.longitude AS x,
        f.fuel_type,
        f.price,
        f.last_updated_year,
        f.last_updated_month,
        f.last_updated_day,
        f.last_updated_time,
        f.members_only
    FROM fuel_prices f
    JOIN stations s ON f.station_id = s.station_id
    WHERE s.latitude IS NOT NULL AND s.longitude IS NOT NULL
    LIMIT 10
""").df()

print(result)

# Executing SQL command to list all tables currently available in the DuckDB database
con.execute("SHOW TABLES").df()

# Executing SQL command to display the structure of the 'stations' table
con.execute("DESCRIBE stations").df()

# Executing SQL command to display the structure of the 'fuel_prices' table
con.execute("DESCRIBE fuel_prices").df()

# Executing SQL query to count the total number of records
con.execute("SELECT COUNT(*) FROM stations").df()
con.execute("SELECT COUNT(*) FROM fuel_prices").df()

# Example query
con.execute("""
    SELECT
        s.station_name, s.suburb, s.latitude, s.longitude,
        f.fuel_type, f.price, f.last_updated_time
    FROM fuel_prices f
    JOIN stations s ON f.station_id = s.station_id
    WHERE s.latitude IS NOT NULL
""").df()

# Example query for retrieving data of paricular date
con.execute("""SELECT
    s.station_name,
    s.suburb,
    s.latitude AS y,
    s.longitude AS x,
    f.fuel_type,
    f.price,
    f.last_updated_time
FROM fuel_prices f
JOIN stations s ON f.station_id = s.station_id
WHERE f.last_updated_day = 24
  AND f.last_updated_month = 01
  AND f.last_updated_year = 2025
ORDER BY f.price DESC;""").df()

"""### Requirements File Generation"""

# pip freeze > requirements.txt
